### ISSUE TITLE
Tab highlighting is not working

### ISSUE THREAD

**Issue by MischaTheEvil** [dalyons/redmine-todos-scrum-plugin#1]
The project-menu item (tab) hightlighting when it's the currently active project-module isn't working. This can be fixed pretty easily by changing the following two lines in init.rb from:

<pre>
  menu :top_menu, :todo_lists, { :controller => 'mytodos', :action => 'index' }, :caption => :my_todos_title #, :public => false     
  menu :project_menu, :todo_lists, {:controller => 'todos', :action => 'index'}, :caption => :project_todos_title, :after => :new_issue, :param => :project_id
</pre> to:
<pre>
  menu :top_menu, :mytodos, { :controller => 'mytodos', :action => 'index' }, :caption => :my_todos_title #, :public => false     
  menu :project_menu, :todos, {:controller => 'todos', :action => 'index'}, :caption => :project_todos_title, :after => :new_issue, :param => :project_id
</pre>

This will change the CSS-classes used for the links from respectively `todo-lists` for both links to `mytodos` for the top-menu link and `todos` for the project-menu link.

HTH...

**Comment by MischaTheEvil** [comment]
Note: I had to change the code-structure a bit to let Github handle the pre-tags correctly... :-S

**Comment by dalyons** [comment]
Hey thanks for picking that up(and the fix :p)! I hadn't even noticed, but after you pointed it out it became annoying :)

**Comment by MischaTheEvil** [comment]
Thanks for the change... I came around this while working on the support for this plugin in the Squeejee Redmine theme (see http://www.redmine.org/wiki/redmine/ThemeSqueejee#020-Extension-Compatibility). In release 0.2.0 of the theme I had anticipated for this change in your plugin, so it doesn't need a new release (happily :)...

Keep up the good work... :thumbsup:

Kind regards,

Mischa.
