### ISSUE TITLE
NameError (undefined local variable or method `todo' for #<TodosController:0x4490080>)

### ISSUE THREAD

**Issue by kunalashar** [dalyons/redmine-todos-scrum-plugin#12]
I can create a new Todo, assign a due date to it and a task that it refers to. But when I click the '+' to add a child to the todo, I get the following error:

Processing TodosController#new (for IPADDRESS at 2009-11-27 13:01:27) [GET]
  Session ID: 9c02f36ed49d5078b442cbed88057d5e
  Parameters: {"project_id"=>"pe-project", "action"=>"new", "issue_id"=>"367", "controller"=>"todos", "parent_id"=>"5"}

NameError (undefined local variable or method `todo' for #<TodosController:0x4420ca8>):
    /vendor/plugins/redmine_todos_plugin/app/controllers/todos_controller.rb:69:in`new'
    /vendor/rails/actionpack/lib/action_controller/base.rb:1166:in `send'
    /vendor/rails/actionpack/lib/action_controller/base.rb:1166:in`perform_action_without_filters'
    /vendor/rails/actionpack/lib/action_controller/filters.rb:579:in `call_filters'
    /vendor/rails/actionpack/lib/action_controller/filters.rb:572:in`perform_action_without_benchmark'
    /vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
    D:/Tools/ruby/lib/ruby/1.8/benchmark.rb:293:in`measure'
    /vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
    /vendor/rails/actionpack/lib/action_controller/rescue.rb:201:in`perform_action_without_caching'
    /vendor/rails/actionpack/lib/action_controller/caching/sql_cache.rb:13:in `perform_action'
    /vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:33:in`cache'
    /vendor/rails/activerecord/lib/active_record/query_cache.rb:8:in `cache'
    /vendor/rails/actionpack/lib/action_controller/caching/sql_cache.rb:12:in`perform_action'
    /vendor/rails/actionpack/lib/action_controller/base.rb:529:in `send'
    /vendor/rails/actionpack/lib/action_controller/base.rb:529:in`process_without_filters'
    /vendor/rails/actionpack/lib/action_controller/filters.rb:568:in `process_without_session_management_support'
    /vendor/rails/actionpack/lib/action_controller/session_management.rb:130:in`process'
    /vendor/rails/actionpack/lib/action_controller/base.rb:389:in `process'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:149:in`handle_request'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:107:in `dispatch'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:104:in`synchronize'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:104:in `dispatch'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:120:in`dispatch_cgi'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:35:in `dispatch'
    /vendor/rails/railties/lib/webrick_server.rb:112:in`handle_dispatch'
    /vendor/rails/railties/lib/webrick_server.rb:78:in `service'
    D:/Tools/ruby/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
    D:/Tools/ruby/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
    D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
    D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:162:in `start'
    D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
    D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:95:in `start'
    D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:92:in`each'
    D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:92:in `start'
    D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:23:in`start'
    D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:82:in `start'
    /vendor/rails/railties/lib/webrick_server.rb:62:in`dispatch'
    /vendor/rails/railties/lib/commands/servers/webrick.rb:66
    D:/Tools/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    D:/Tools/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    /vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
    /vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in`new_constants_in'
    /vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
    /vendor/rails/railties/lib/commands/server.rb:39
    D:/Tools/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    D:/Tools/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    script/server:3

Rendering D:/Tools/redmine-0.8.5/public/500.html (500 Internal Server Error)

**Comment by dalyons** [comment]
Can you try this with redmine 0.9.x and let me know if its still a problem?
