### ISSUE TITLE
Menu shows "My Todos" link for not-allowed users

### ISSUE THREAD

**Issue by fnordfish** [dalyons/redmine-todos-scrum-plugin#13]
This patch adds a check, if the current user is allowed to "use_personal_todos"

<pre>
diff --git a/init.rb b/init.rb
index 90bc35a..a926102 100644
--- a/init.rb
+++ b/init.rb
@@ -55,7 +55,10 @@ Redmine::Plugin.register :redmine_todos_plugin do
   end
  
   menu :top_menu, :mytodos, { :controller => 'mytodos', :action => 'index' }, 
-      :caption => :my_todos_title #, :public => false
+       :caption => :my_todos_title,
+       :if => Proc.new {
+          User.current.allowed_to?(:use_personal_todos, nil, :global => true)
+        }
      
   menu :project_menu, :todos, {:controller => 'todos', :action => 'index'}, 
       :caption => :label_todo_plural, :after => :new_issue, :param => :project_id
</pre>

**Comment by dalyons** [comment]
Thank you for this, have applied this patch! :)
