### ISSUE TITLE
My Todos gives an internal error

### ISSUE THREAD

**Issue by OffbeatPlanet** [dalyons/redmine-todos-scrum-plugin#14]
I just installed this plugin following instructions in the readme. When I click on My Todos it shows the following error:
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your redMine administrator for assistance.

Back

Any ideas?

**Comment by OffbeatPlanet** [comment]
I found the answer here:
http://github.com/gmiklaszewski/redmine-todos-scrum-plugin/commit/61dd31bdcf5713063df744d2e243ca7eef53c267

**Comment by dalyons** [comment]
sorry, just so i can track this one down, what rails & redmine version are you using?

I cant reproduce it on redmine 0.9.x with rails 2.3.5 - I want to see who this affects

**Comment by TienTran** [comment]
I have same error .. 
I installed the plug-in on redmin 0.9.1 with rails 2.3.5
I can't see the list of issues in the projects, but whenever I click on Activity tab or on any issue --> Internal error

**Comment by TienTran** [comment]
I just upgraded redmine to 0.9.2, installed new copy of todolist and it works.
Thanks for the nice plugin.

**Comment by dalyons** [comment]
thanks for the feedback! I wonder what changed between 0.9.1 and 0.9.2...
