### ISSUE TITLE
Internal error, when My Todos

### ISSUE THREAD

**Issue by kimse** [dalyons/redmine-todos-scrum-plugin#17]
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your redMine administrator for assistan

Here is how it's installed: 
projects:/usr/local/lib/redmine-0.8/vendor/plugins# git clone git://github.com/dalyons/redmine-todos-scrum-plugin.git redmine_todos_plugin
Initialized empty Git repository in /usr/local/lib/redmine-0.8/vendor/plugins/redmine_todos_plugin/.git/
remote: Counting objects: 856, done.
remote: Compressing objects: 100% (551/551), done.
remote: Total 856 (delta 471), reused 399 (delta 235)
Receiving objects: 100% (856/856), 401.50 KiB | 402 KiB/s, done.
Resolving deltas: 100% (471/471), done.
projects:/usr/local/lib/redmine-0.8/vendor/plugins# rake db:migrate_plugins RAILS_ENV=production
(in /usr/local/lib/redmine-0.8)
Migrating engines...
Migrating actionwebservice...
Migrating acts_as_activity_provider...
Migrating acts_as_attachable...
Migrating acts_as_customizable...
Migrating acts_as_event...
Migrating acts_as_list...
Migrating acts_as_searchable...
Migrating acts_as_tree...
Migrating acts_as_versioned...
Migrating acts_as_watchable...
Migrating classic_pagination...
Migrating coderay-0.7.6.227...
Migrating gloc-1.1.0...
Migrating gravatar...
Migrating redmine_todos_plugin...
Migrating rfpdf...
Migrating ruby-net-ldap-0.0.4...
Migrating timesheet_plugin...
projects:/usr/local/lib/redmine-0.8/vendor/plugins# /etc/init.d/apache2 restart
Restarting web server: apache2 ... waiting .
projects:/usr/local/lib/redmine-0.8/vendor/plugins#

Versions:
Redmine 0.8.7.stable.3297
ruby 1.8.7
rack (1.1.0)
rails (2.1.2)
rake (0.8.7)
Debian (5.0.3)

**Comment by dalyons** [comment]
kimse - as it says in the README, you need at least rails 2.2.1 to run the plugin. I would suggest either installing 2.2.1 and chaging your RAILS_VERSION in config/enviroment.rb, or upgrade to redmine 0.9.x (which uses rails 2.3.5)
