### ISSUE TITLE
Ability to attach a todo to a project

### ISSUE THREAD

**Issue by martinlindhe** [dalyons/redmine-todos-scrum-plugin#22]
In order to use optinally use this plugin as a quick and dirty task tracker associated with a redmine project, it would be great if one could also attach/associate a todo task with a project.

This would later make way for the possibility to show todo creation/completion entries in a project's activity log

**Comment by dalyons** [comment]
Er, you can... thats the whole reason i built it in the first place :)
If you go in to the settings for a project, and in modules, and enable the todos module, you should see a 'todos' tab on the project where you can add todos against the project.
They then come up on the 'My todos' screen aswell, under the project headings.

**Comment by martinlindhe** [comment]
Oh how stupid of me :) i forgot to enable the module for the projects and only saw the "My todos" in the top navigation list

i'll make a separete feature request of the second part of my orginal message
