### ISSUE TITLE
Is the version 0.0.4.1 available at github?

### ISSUE THREAD

**Issue by hooke** [dalyons/redmine-todos-scrum-plugin#26]
Just cloned the repository of redmine-todos-scrum-plugin from github. 
As far as I understood, last version is 0.0.4.1, but init.rb states that version is 0.0.3.9
So what the version of the plugin in repository is?
Maybe init.rb should be corrected for proper version?

**Comment by dalyons** [comment]
Yes, my bad. I forgot to update the version in init.rb. Have done now, ill tag it properly once i clear up another bug!
