### ISSUE TITLE
db:migrate_plugins fails with "translation missing en"

### ISSUE THREAD

**Issue by vide** [dalyons/redmine-todos-scrum-plugin#28]
Hi

I've just updated an old Redmine SVN installation to stable 0.9.4, no problems. I've tried to update the Scrum todos list plugin (to the most recent git revision) but it fails on migrating the DB

<code>
Migrating redmine_todos_plugin...
==  RemoveOldTodoAssociations: migrating ======================================
rake aborted!
An error has occurred, all later migrations canceled:

Validation failed: translation missing: en, field_text is too short (minimum is 1 characters)
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/validations.rb:1090:in `save_without_dirty!'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/dirty.rb:87:in`save_without_transactions!'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/transactions.rb:200:in `save!'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in`transaction'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/transactions.rb:182:in `transaction'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/transactions.rb:200:in`save!'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/transactions.rb:200:in`save!'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/base.rb:2635:in `update_attributes!'
/var/www/redmine-0.9.4/vendor/plugins/redmine_todos_plugin/db/migrate/006_remove_old_todo_associations.rb:6:in`up_without_benchmarks'
/var/www/redmine-0.9.4/vendor/plugins/redmine_todos_plugin/db/migrate/006_remove_old_todo_associations.rb:5:in `each'
/var/www/redmine-0.9.4/vendor/plugins/redmine_todos_plugin/db/migrate/006_remove_old_todo_associations.rb:5:in`up_without_benchmarks'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:282:in `send'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:282:in`migrate'
/usr/lib/ruby/1.8/benchmark.rb:293:in `measure'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:282:in`migrate'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:365:in `__send__'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:365:in`migrate'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:486:in `migrate'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:562:in`call'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:562:in `ddl_transaction'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:485:in`migrate'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:472:in `each'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:472:in`migrate'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:400:in `up'
/var/www/redmine-0.9.4/vendor/rails/activerecord/lib/active_record/migration.rb:383:in`migrate'
/var/www/redmine-0.9.4/vendor/plugins/engines/lib/engines/plugin/migrator.rb:20:in `migrate_plugin'
/var/www/redmine-0.9.4/config/../vendor/plugins/engines/lib/engines/plugin.rb:93:in`migrate'
/var/www/redmine-0.9.4/lib/tasks/migrate_plugins.rake:8
/var/www/redmine-0.9.4/lib/tasks/migrate_plugins.rake:5:in `each'
/var/www/redmine-0.9.4/lib/tasks/migrate_plugins.rake:5
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/var/lib/gems/1.8/gems/rake-0.8.7/bin/rake:31
/var/lib/gems/1.8/bin/rake:19:in `load'
/var/lib/gems/1.8/bin/rake:19
</code>

**Comment by vide** [comment]
anyway the plugin seems to work

**Comment by dalyons** [comment]
yeah, that just means you had an existing todo in the system that is blank, has no todo text.
That shouldnt have been allowed, and now it isnt :)

Someone else already had this issue - see here for how to get rid of blank todos:
http://github.com/dalyons/redmine-todos-scrum-plugin/issues/closed#issue/6/comment/65919

**Comment by vide** [comment]
you were right, the fix proposed (giving a value to the blank todos) worked, I could complete the plugin migration. Thanks!
