### ISSUE TITLE
Error Occurs Post Installation when attempting to view Issues

### ISSUE THREAD

**Issue by ChrisMcKee** [dalyons/redmine-todos-scrum-plugin#29]
The plugin seems to work fine elsewhere but when you try to view an issue it throws the 500 page and this is in my production log...

<pre>

Processing IssuesController#show (for 10.249.1.77 at 2010-05-18 14:47:30) [GET]
  Parameters: {"action"=>"show", "id"=>"1121", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/show.rhtml

ActionView::TemplateError (Can only render or redirect once per action) on line #17 of app/views/layouts/base.rhtml:
14:       body {behavior: url(<%= stylesheet_path "csshover.htc" %>);}
15:     </style>
16: <![endif]-->
17: <%= call_hook :view_layouts_base_html_head %>
18: 
19: <%= yield :header_tags -%>
20: </head>

    lib/redmine/hook.rb:113:in `send'
    lib/redmine/hook.rb:113:in `view_layouts_base_html_head'
    lib/redmine/hook.rb:63:in `send'
    lib/redmine/hook.rb:63:in `call_hook'
    lib/redmine/hook.rb:63:in `each'
    lib/redmine/hook.rb:63:in `call_hook'
    lib/redmine/hook.rb:60:in `call_hook'
    lib/redmine/hook.rb:144:in `call_hook'
    app/views/layouts/base.rhtml:17:in `_run_rhtml_app47views47layouts47base46rhtml'
    app/controllers/issues_controller.rb:116:in `show_without_todo'
    app/controllers/issues_controller.rb:115:in `show_without_todo'

Rendering C:/BitNami-RedmineStack/apps/redmine/public/500.html (500 Internal Server Error)

</pre>

**Comment by eLco** [comment]
Version 0.0.3.6 of plugin (marked stable) works fine with redmine 0.9.4, for me.
But with version 0.0.4.1 I've same error.

From plugin page - http://www.redmine.org/boards/3/topics/4070?page=4#message-9725

Nicolas Zinopoulos has same error with version 0.0.3.9.
So it's seems to me like problem is between 0.0.3.6 and 0.0.3.9.
