### ISSUE TITLE
Small wording fix in title popup when you mouse over "trash" icon

### ISSUE THREAD

**Issue by meglio** [dalyons/redmine-todos-scrum-plugin#32]
Simple screenshot to explain the issue:
http://i30.tinypic.com/2yjsv7k.png

**Comment by dalyons** [comment]
do you think? I never leave spaces before my brackets in writing. Maybe I was just taught wrong? :p. I think im going to leave it as-is, just because thats the way im used to. (although if it bothers you heaps i can change it!)
