### ISSUE TITLE
translation missing: de, label_related_todos

### ISSUE THREAD

**Issue by qno** [dalyons/redmine-todos-scrum-plugin#37]
Version: Redmine 1.0.1.stable

in issues - detail view:  there is an translation missing: de, label_related_todos error

in vendor/plugins/redmine_todos_plugin/app/views/issues/_todos.html.erb line with content  <p><strong><%= l(:label_related_todos) %></strong></p>
method l(:label_related_todos) doesn't reach the content from files vendor/plugins/redmine_todos_plugin/lang/   (en.yml, de.yml etc.)

Can someone please fix this? I don't know how to that.
Thank you.

**Comment by jensk** [comment]
https://github.com/dalyons/redmine-todos-scrum-plugin/pull/36

**Comment by qno** [comment]
hello jensk,
thank you for your response.
I've already noticed the missing translation entries and fixed that by myself.
But this doesn't solve the problem. The _todos.html.erb doesn't get the necessary entries from the translation files.

**Comment by qno** [comment]
Sorry i've erroneously closed the issue. I've reopend it in Issue #38.
