### ISSUE TITLE
Displaying related ToDos in Issue view

### ISSUE THREAD

**Issue by nowhereman** [dalyons/redmine-todos-scrum-plugin#4]
It'll be cool if in issue view we can show related todos like related issues.

**Comment by nowhereman** [comment]
My fork of redmine-todos-scrum-plugin (http://github.com/nowhereman/redmine-todos-scrum-plugin/tree/master) adds this feature.

**Comment by dalyons** [comment]
iv'e merged in nowhereman's excellent work on this as of 0.0.3.9!
