### ISSUE TITLE
Translation missing ?

### ISSUE THREAD

**Issue by volpone** [dalyons/redmine-todos-scrum-plugin#9]
I've installed ToDo lists plugin but have an issue with localization (Redmine locale in french).

I've got a translation missing: fr, project message in the main project menu (Todo Link).
Also others messages are not translated (from english). 
I've checked 2 points:

1) Name of the pugin install directory: redmine_todos_plugin
2) Strings and localization files in lang and locale are existing:
=> /home/extranet/redmine/vendor/plugins/redmine_todos_plugin/lang/en.yml
=> /home/extranet/redmine/vendor/plugins/redmine_todos_plugin/lang/fr.yml

My envrinonment: 
Debian etch 4.0 
ToDo List : 0.0.3.6 (as last 0..0.3.9 version not available for download ?) 
Rails: 2.3.4 
Redmine: 0.8.6.devel.3022 (MySQL) 

Regards

**Comment by volpone** [comment]
The problems was i was running 0.0..3.1. (and not 0.0.3.6)
With some editing in fr.yml it works now but without accentuated suport.
I would like to upgrade to  the last 0.0.3.9 version but i don't know if there is zip ot tar available.

**Comment by dalyons** [comment]
you can just use git to get the newest version(which is 0.0.3.9):

(from the readme)
git clone git://github.com/dalyons/redmine-todos-scrum-plugin.git redmine_todos_plugin
